### ISSUE TITLE
New Version Not Downloading Some Users (404)

### ISSUE THREAD

**Issue by JackLamber** [Nekromateion/RedGifs-Gfycat-Downloader#8]
So I've been using the rewrite for a while but for some users it downloads a few videos then gives out this error. With some users it doesn't download any files and give the same error.

`System.Net.WebException: The remote server returned an error: (404) Not Found.
   at System.Net.HttpWebRequest.GetResponse()
   at System.Net.WebClient.GetWebResponse(WebRequest request)
   at System.Net.WebClient.DownloadBits(WebRequest request, Stream writeStream)
   at System.Net.WebClient.DownloadFile(Uri address, String fileName)
   at GfycatDownloader_Rewrite_DNCore.RedGifs.DownloadUser(String userId, String type, Int32 minLikes)
   at GfycatDownloader_Rewrite_DNCore.Program.Main(String[] args)` 

Also I'm not sure how to change the destination folder because `RedGifs_Rewrite_DNCore freshconfig` isn't doing anything for me

**Comment by JackLamber** [comment]
> Currently you can not change the destination folder.
> 
> Could you give me an example on a user that does not download if possible? @JackLamber

Sure, "loveofmylife69" It runs for a while then spits out the error. There is another weird error that pops up from time to time but it's not common. Also I set `minlikes=0` and it works fine

**Comment by Nekromateion** [comment]
Hey there,
I recently found out that [Gallery-DL](https://github.com/mikf/gallery-dl) supports redgifs so please use that, since I don't have the time to maintain this project anymore.
